### PR TITLE
Permissions for developers

### PR DESCRIPTION
**Pull request by cabutlermit**
#### Developer Checklist

- [X] The README contains any additional info needed outside of the terraform docs generated
- [N/A] Any special variables have values configured in AWS SSM
- [N/A] Stakeholder approval has been confirmed (or is not needed)

#### What does this PR do?

It creates a custom Permission Set for the developers who need access to AWS in our AWS Organization (e.g., folks in EngX, EntSys, and the data/metadata engineers in InfraEng). The Permission Set is defined in a `.json` file and can be easily modified in the future to adjust permissions as needed. 

It also creates associations between the AWS SSO Group (created manually in the Console UI) and the AWS Accounts to which these folks need access. As with other groups, it provides the default ReadOnly role in addition to the role defined by the custom Permission Set.

Finally, the code is ready to assign the developers PowerUser level access to any new AWS Accounts that are created in the Sandbox OU -- we will just need to add those account numbers to the variable in TfC once they have been created.

#### Helpful background context

This is a first draft of the allowed Actions for the devs. This will need to be refined once they start to use this role to access AWS.

#### What are the relevant tickets?

[https://mitlibraries.atlassian.net/browse/IN-439](https://mitlibraries.atlassian.net/browse/IN-439)

#### Requires Database Migrations?

NO

#### Includes new or updated dependencies?

NO

### CODE REVIEW

**Review by zotoMIT — COMMENTED** [review]
Looks like your tfcloud plan is stuck(probably waiting for credentials)

**Comment by cabutlermit** [comment]
> Looks like your tfcloud plan is stuck(probably waiting for credentials)

yup. Just updated the creds and it looks like it's running now...

**Review by zotoMIT — APPROVED** [review]
LGTM

**Review by tim-rix — APPROVED** [review]
Looks good to me

**Pull request merged**
