### PR TITLE
Workflows update

### PR DESCRIPTION
**Pull request by zotoMIT**
#### Developer Checklist

- [X] The README contains the correct list of dependencies, inputs, and outputs (e.g., `terraform-docs markdown .` has been run and copied)
- [NA] Any special variables have values configured in the Terraform Cloud workspace
- [NA] Stakeholder approval has been confirmed (or is not needed)

#### What does this PR do?

This PR brings in changes from the updated template, including automatic docs generation, and checkov checks.  

#### Helpful background context

This change is only a documentation/github change, and shouldn't require a redeploy in terraform. 

#### What are the relevant tickets?

NA

#### Requires Database Migrations?

NO

#### Includes new or updated dependencies?

NO

### CODE REVIEW

**Comment by zotoMIT** [comment]
Interesting, it still wants to do a terraform apply/plan here with credentials, guess because i touched the terraform code?

**Comment by zotoMIT** [comment]
Added credentials so it can plan.

**Comment by cabutlermit** [comment]
> Interesting, it still wants to do a terraform apply/plan here with credentials, guess because i touched the terraform code?

I'm not surprised. Sort of a good test of whether our code is really building immutable infrastructure and verifies that there hasn't been any drift...

**Review by cabutlermit — APPROVED** [review]
looks good.

**Pull request merged**
